---
title: "DSCI 310: Historical Horse Population in Canada"
author: "Tiffany Timbers & Jordan Bourak"
date: "2021-11-22"
format: 
  html:
    toc: true
    toc-depth: 3
    number-sections: true
    code-fold: false
  pdf:
    number-sections: true
bibliography: references.bib
csl: apa.csl
editor: 
  markdown: 
    wrap: 72
---

```{python}
#| echo: false
import pandas as pd
from IPython.display import Markdown, display
from tabulate import tabulate
```

## Aim

This project explores the historical population of horses in Canada
between 1906 and 1972 for each province.

## Data

Horse population data were sourced from the [Government of Canada's Open
Data website](http://open.canada.ca/en/open-data)
(@governmentofcanada2017a; @governmentofcanada2017b).

## Methods

The Python programming language (Van Rossum and Drake 2009) and the
following Python packages were used to perform the analysis: pandas
[@mckinney2010], altair [@vanderplas2018], click [@team2020], as well as
this Quarto [@allaire2022].

Note: this report is adapted from [@timbers2022]

## Results

![Horse populations for all provinces in Canada from
1906–1972.](../results/horse_pops_plot.png){#fig-horse-pops
fig-cap="Horse populations for all provinces in Canada from 1906–1972."}

We can see from @fig-horse-pops. that Ontario, Saskatchewan and Alberta
have had the highest horse populations in Canada. All provinces have had
a decline in horse populations since 1940. This is likely due to the
rebound of the Canadian automotive industry after the Great Depression
and the Second World War. An interesting follow-up visualisation would
be car sales per year for each Province over the time period visualised
above to further support this hypothesis.

Suppose we were interested in looking in more closely at the province
with the highest spread (in terms of standard deviation) of horse
populations. We present the standard deviations in Table @tbl-horse-sd.

Table @tbl-horse-sd

```{python}
#| label: tbl-horse-sd
#| tbl-cap: "Standard deviation of historical (1906–1972) horse populations for each Canadian province."
#| echo: false

horses_sd_table = pd.read_csv("./results/horses_sd.csv")
largest_sd = horses_sd_table['Province'].values[0]
Markdown(horses_sd_table.to_markdown(index=False))
```

Note that we define standard deviation (of a sample) as

$$s = \sqrt{\frac{\sum_{i=1}^N (x_i - \overline{x})^2}{N-1} }$$

Additionally, note that in @tbl-horse-sd we consider the sample standard
deviation of the number of horses during the same time span as
@fig-horse-sd.

![Horse populations for the province with the largest standard
deviation.](../results/horse_pops_plot_largest_sd.png){#fig-horse-sd
width="65%"}

@fig-horse-sd zooms in for the province of
`{python} horses_sd_table.iloc[0]['Province']`, which had largest spread
of values in terms of standard deviation.

## References
